version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    scale: 1
    mem_limit: 512M
    env_file:
      - .env
    volumes:
      - .:/usr/src/app # mount the app folder to container | this is for development only
      - /usr/src/app/node_modules # node_modules should be mounted as volume to avoid installing dependencies in container
    command: pnpm run start api
    networks:
      - daedalus_network
    expose:
      - "5000"

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    scale: 2
    mem_limit: 512M
    env_file:
      - .env
    volumes:
      - .:/usr/src/app # mount the app folder to container | this is for development only
      - /usr/src/app/node_modules # node_modules should be mounted as volume to avoid installing dependencies in container
    command: pnpm run start auth
    networks:
      - daedalus_network
    expose:
      - "5001"

  template:
    build:
      context: .
      dockerfile: apps/template/Dockerfile
    scale: 2
    mem_limit: 512M
    env_file:
      - .env
    volumes:
      - .:/usr/src/app # mount the app folder to container | this is for development only
      - /usr/src/app/node_modules # node_modules should be mounted as volume to avoid installing dependencies in container
    command: pnpm run start template
    networks:
      - daedalus_network
    expose:
      - "5002"

  nginx:
    image: nginx
    ports:
      - "80:80"
    mem_limit: 1G
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - auth
      - template
    networks:
      - daedalus_network

networks:
  daedalus_network:
    driver: bridge
