services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    mem_limit: 1G
    env_file:
      - .env
    volumes:
      - .:/usr/src/app # mount the app folder to container | this is for development only
      - /usr/src/app/node_modules # node_modules should be mounted as volume to avoid installing dependencies in container
    command: pnpm run start api

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    mem_limit: 1G
    env_file:
      - .env
    volumes:
      - .:/usr/src/app # mount the app folder to container | this is for development only
      - /usr/src/app/node_modules # node_modules should be mounted as volume to avoid installing dependencies in container
    command: pnpm run start auth

  template:
    build:
      context: .
      dockerfile: apps/template/Dockerfile
    mem_limit: 1G
    env_file:
      - .env
    volumes:
      - .:/usr/src/app # mount the app folder to container | this is for development only
      - /usr/src/app/node_modules # node_modules should be mounted as volume to avoid installing dependencies in container
    command: pnpm run start template

  nginx:
    image: nginx
    ports:
      - "80:80"
    mem_limit: 1G
    volumes:
      - ./nginx.conf:/etc/ngnix/nginx.conf
    depends_on:
      - api
      - auth
      - template
    networks:
      - daedalus_network

networks:
  daedalus_network:
    driver: bridge